"""Species classifier contract, Phase 6 compact model, and crop pipeline."""

from .classifier import (
    DEMO_DATA_LABEL,
    STUB_CLASSIFIER_VERSION,
    CancellationToken,
    ClassificationResult,
    ClassificationStatus,
    ClassifierError,
    ClassifierInput,
    DummyClassifier,
    DummyScenario,
    MalformedImageError,
    SpeciesClassifier,
    SpeciesSuggestion,
)
from .pipeline import ClassificationPipeline, ClassificationRun, format_diagnostic
from .compact import (
    CatalogFeatureClassifier,
    CompactSpeciesClassifier,
    ModelMetadata,
    RealSpeciesClassifier,
    UnavailableSpeciesClassifier,
    extract_features,
)
from .embedding import (
    EmbeddingModelError,
    EmbeddingModelMetadata,
    MobileNetV2Embedder,
    load_embedding_model,
    preprocess_image,
)
from .fewshot import (
    CAMPUS_ARTIFACT_FORMAT,
    CAMPUS_MODEL_ID,
    CampusFewShotClassifier,
    CampusModelMetadata,
    EnrollmentError,
    build_enrollment_artifact,
    campus_label_id,
    perceptual_hash,
    score_labels,
)

__all__ = [
    "CancellationToken",
    "CatalogFeatureClassifier",
    "CAMPUS_ARTIFACT_FORMAT",
    "CAMPUS_MODEL_ID",
    "CampusFewShotClassifier",
    "CampusModelMetadata",
    "CompactSpeciesClassifier",
    "ClassificationPipeline",
    "ClassificationResult",
    "ClassificationRun",
    "ClassificationStatus",
    "ClassifierError",
    "ClassifierInput",
    "DEMO_DATA_LABEL",
    "DummyClassifier",
    "DummyScenario",
    "EmbeddingModelError",
    "EmbeddingModelMetadata",
    "EnrollmentError",
    "MalformedImageError",
    "ModelMetadata",
    "MobileNetV2Embedder",
    "load_embedding_model",
    "preprocess_image",
    "RealSpeciesClassifier",
    "STUB_CLASSIFIER_VERSION",
    "SpeciesClassifier",
    "SpeciesSuggestion",
    "UnavailableSpeciesClassifier",
    "extract_features",
    "build_enrollment_artifact",
    "campus_label_id",
    "perceptual_hash",
    "score_labels",
    "format_diagnostic",
]
